<?php

declare(strict_types=1);

namespace SymPress\Runtime\Filesystem;

use SymPress\Runtime\Config\Config;
use SymPress\Runtime\Console\Io;
use Symfony\Component\Filesystem\Path;

final readonly class OverwritePolicy
{
    public const string MARKER = '@generated by sympress/runtime';

    public function __construct(private Config $config, private Paths $paths, private Io $io)
    {
    }

    public function shouldOverwrite(string $file, bool $force = false): bool
    {
        if (is_dir($file) || is_link($file)) {
            return false;
        }
        if (!file_exists($file) || $force) {
            return true;
        }
        $setting = $this->config['prevent-overwrite']->unwrapOrFallback(false);
        if ($setting === 'ask') {
            return $this->io->askConfirm(basename($file) . ' exists. Overwrite it?', true);
        }
        if ($setting === true) {
            return false;
        }
        if (is_array($setting)) {
            $relative = Path::makeRelative($file, $this->paths->root());
            if (str_starts_with($relative, '../')) {
                return false;
            }
            foreach ($setting as $pattern) {
                if (is_string($pattern) && fnmatch(trim(str_replace('\\', '/', $pattern), '/'), $relative, FNM_NOESCAPE)) {
                    return false;
                }
            }
        }
        if ($this->config['compatibility-profile']->is('native')) {
            $content = is_readable($file) ? file_get_contents($file) : false;

            return is_string($content) && str_contains($content, self::MARKER);
        }

        return true;
    }
}
