<?php

declare(strict_types=1);

namespace SymPress\Runtime\Tests\Integration;

use SymPress\Runtime\Env\EnvCacheFormat;
use SymPress\Runtime\EnvironmentInspection;
use SymPress\Runtime\Tests\Support\TemporaryProject;
use Symfony\Component\Process\Process;

// phpcs:disable SlevomatCodingStandard.Variables.DisallowSuperGlobalVariable -- The test proves preservation of the caller's full environment boundary.

final class EnvironmentInspectionTest extends TemporaryProject
{
    public function testConfiguredChainAndProcessValuesAreReadWithoutChangingTheCaller(): void
    {
        $this->write('composer.json', json_encode(['extra' => ['sympress-runtime' => ['env-file' => 'site.env']]], JSON_THROW_ON_ERROR));
        $this->write('site.env', "WP_ENVIRONMENT_TYPE=production\nRTV_INSPECTION=base\n");
        $this->write('site.env.local', "RTV_INSPECTION=local\n");
        $this->write('site.env.production', "RTV_INSPECTION=production\n");
        $this->write('site.env.production.local', "RTV_INSPECTION=last\n");
        $this->write('wp-config.php', '<?php throw new RuntimeException("must not execute");');
        $environment = $_ENV;
        $server = $_SERVER;
        $process = getenv();
        $result = EnvironmentInspection::inspect($this->root, ['RTV_INSPECTION', 'RTV_ABSENT']);
        self::assertSame(['environment' => 'production', 'values' => ['RTV_INSPECTION' => 'last', 'RTV_ABSENT' => null], 'source' => 'files'], $result);
        self::assertSame($environment, $_ENV);
        self::assertSame($server, $_SERVER);
        self::assertSame($process, getenv());
        self::assertFalse(defined('WP_ENVIRONMENT_TYPE'));
        self::assertFileDoesNotExist($this->root . '/.env.cached.php');
        self::assertDirectoryDoesNotExist($this->root . '/var');
        putenv('RTV_INSPECTION=process');
        try {
            self::assertSame('process', EnvironmentInspection::inspect($this->root, ['RTV_INSPECTION'])['values']['RTV_INSPECTION']);
            self::assertSame('process', getenv('RTV_INSPECTION'));
        } finally {
            putenv('RTV_INSPECTION');
        }
    }

    public function testDumpAndCacheRefreshInterpolationWithoutParserOrFingerprintOracle(): void
    {
        $this->write('composer.json', '{}');
        $this->write('.env', 'RTV_INSPECTION=${RTV_SECRET:-fallback}' . "\nRTV_STATIC=stable\n");
        $autoload = dirname(__DIR__, 2) . '/vendor/autoload.php';
        $build = new Process([PHP_BINARY, '-r', 'require ' . var_export($autoload, true) . '; $r = new SymPress\\Runtime\\Env\\EnvReader(); $r->loadChain(); $r->dumpCached(".env.cached.php"); $r->dumpCached(".env.dump.php", immutable:true);'], $this->root, ['RTV_SECRET' => 'dictionary-word']);
        $build->mustRun();
        foreach (['.env.cached.php', '.env.dump.php'] as $artifact) {
            $bytes = file_get_contents($this->root . '/' . $artifact);
            self::assertIsString($bytes);
            self::assertStringNotContainsString('dictionary-word', $bytes);
            $payload = EnvCacheFormat::read($this->root . '/' . $artifact, dataOnly: true);
            foreach ($payload['interpolation']['dependencies'] as $dependency) {
                self::assertSame(['marker'], array_keys($dependency));
                foreach (['dictionary-word', 'password', 'secret'] as $guess) {
                    self::assertStringNotContainsString(hash('sha256', $dependency['marker'] . "\0" . $guess), $bytes);
                }
            }
        }
        $inspect = 'require ' . var_export($autoload, true) . '; $r = SymPress\\Runtime\\EnvironmentInspection::inspect(getcwd(), ["RTV_INSPECTION"]); echo json_encode([$r, class_exists(Symfony\\Component\\Dotenv\\Dotenv::class,false)]);';
        $run = new Process([PHP_BINARY, '-r', $inspect], $this->root, ['RTV_SECRET' => 'rotated-secret']);
        $run->mustRun();
        self::assertSame([['environment' => 'production', 'values' => ['RTV_INSPECTION' => 'rotated-secret'], 'source' => 'dump'], false], json_decode($run->getOutput(), true, flags: JSON_THROW_ON_ERROR));
        unlink($this->root . '/.env.dump.php');
        $run->mustRun();
        self::assertSame('cache', json_decode($run->getOutput(), true, flags: JSON_THROW_ON_ERROR)[0]['source']);
    }

    public function testInspectionRejectsExecutableArtifactAndShellSourceBeforeSideEffects(): void
    {
        $this->write('composer.json', '{}');
        $this->write('.env.dump.php', "<?php\n// @generated by sympress/runtime env-cache:v1\nfile_put_contents(__DIR__ . '/executed', 'bad'); return array ('format' => 1,);\n");
        try {
            EnvironmentInspection::inspect($this->root, ['DB_PASSWORD']);
            self::fail('Executable artifact accepted.');
        } catch (\RuntimeException) {
            self::assertFileDoesNotExist($this->root . '/executed');
        }
        unlink($this->root . '/.env.dump.php');
        $this->write('.env', 'DB_PASSWORD=$(touch ' . $this->root . '/executed)' . "\n");
        try {
            EnvironmentInspection::inspect($this->root, ['DB_PASSWORD']);
            self::fail('Shell source accepted.');
        } catch (\RuntimeException $exception) {
            self::assertStringContainsString('refuses shell', $exception->getMessage());
            self::assertFileDoesNotExist($this->root . '/executed');
        }
    }

    public function testLiteralCacheInspectionPreservesEscapedAndBinaryValues(): void
    {
        $payload = ['format' => 1, 'values' => ['quoted' => "'\\\"\$literal", 'binary' => "\0\t\n\r", 'empty' => '', 'negative' => -1, 'null' => null, 'boolean' => true]];
        $this->write('.env.dump.php', EnvCacheFormat::encode($payload));
        self::assertSame($payload, EnvCacheFormat::read($this->root . '/.env.dump.php', dataOnly: true));
    }
}
