<?php

declare(strict_types=1);

namespace SymPress\Runtime\Tests\Integration;

use PHPUnit\Framework\Attributes\DataProvider;
use SymPress\Runtime\Tests\Support\TemporaryProject;
use Symfony\Component\Process\Process;

final class PersistedEnvironmentFormatTest extends TemporaryProject
{
    /** @return array<array-key, mixed> */
    private function runPhp(string $code): array
    {
        $autoload = dirname(__DIR__, 2) . '/vendor/autoload.php';
        $process = new Process([PHP_BINARY, '-r', 'require ' . var_export($autoload, true) . ';' . $code], $this->root, array_fill_keys(['WP_ENV', 'WP_ENVIRONMENT_TYPE', 'WORDPRESS_ENV', 'SYMFONY_DOTENV_VARS', 'RTV_FORMAT_VALUE'], false));
        $process->mustRun();
        $result = json_decode($process->getOutput(), true, flags: JSON_THROW_ON_ERROR);
        self::assertIsArray($result);
        return $result;
    }

    /** @return array<string, mixed> */
    private function legacyPayload(): array
    {
        return [
            'format' => 1,
            'profile' => 'native',
            'environment' => 'production',
            'values' => ['RTV_FORMAT_VALUE' => ['from-02', 'from-02']],
            'loaded' => ['RTV_FORMAT_VALUE'],
            'types' => [],
            'constants' => [],
        ];
    }

    /** @param array<string, mixed> $payload */
    private function writePayload(string $file, array $payload, int $header = 1): void
    {
        $this->write($file, "<?php\n// @generated by sympress/runtime env-cache:v{$header}\nreturn " . var_export($payload, true) . ";\n");
    }

    /** @return iterable<string, array{string}> */
    public static function artifacts(): iterable
    {
        yield 'runtime cache' => ['.env.cached.php'];
        yield 'deployment dump' => ['.env.dump.php'];
    }

    #[DataProvider('artifacts')]
    public function testFormatOneFrom02LoadsWithoutRewritingOrRequiringNewFields(string $file): void
    {
        $payload = $this->legacyPayload();
        $payload['sources'] = $file === '.env.cached.php' ? [$this->root . '/.env' => null] : null;
        $this->writePayload($file, $payload);
        $before = file_get_contents($this->root . '/' . $file);
        $code = '$r = SymPress\\Runtime\\Env\\EnvReader::buildFromCacheDump(' . var_export($file, true) . ', validateSources: ' . var_export($file === '.env.cached.php', true) . '); echo json_encode([$r->hasCachedValues(), $r->read("RTV_FORMAT_VALUE")]);';
        self::assertSame([true, 'from-02'], $this->runPhp($code));
        self::assertSame($before, file_get_contents($this->root . '/' . $file));
    }

    /** @return iterable<string, array{string, mixed, bool}> */
    public static function unsupportedFormats(): iterable
    {
        foreach (['.env.cached.php', '.env.dump.php'] as $file) {
            foreach (['future' => 2, 'older unsupported' => 0, 'noninteger' => '1', 'missing' => null] as $label => $format) {
                yield $file . ' ' . $label => [$file, $format, $file === '.env.cached.php'];
            }
        }
    }

    #[DataProvider('unsupportedFormats')]
    public function testUnsupportedFormatFailsBeforeStaleSourcesCanDiscardIt(string $file, mixed $format, bool $validateSources): void
    {
        $payload = $this->legacyPayload();
        $payload['format'] = $format;
        // Missing source signatures used to bypass format rejection in native caches.
        $this->writePayload($file, $payload);
        $before = file_get_contents($this->root . '/' . $file);
        $code = 'try { SymPress\\Runtime\\Env\\EnvReader::buildFromCacheDump(' . var_export($file, true) . ', validateSources: ' . var_export($validateSources, true) . '); echo "[]"; } catch (RuntimeException $e) { echo json_encode([$e->getMessage(), isset($_ENV["RTV_FORMAT_VALUE"])]); }';
        self::assertSame(['Environment cache format is not supported.', false], $this->runPhp($code));
        self::assertSame($before, file_get_contents($this->root . '/' . $file));
        $write = '$r = new SymPress\\Runtime\\Env\\EnvReader(); $r->write("RTV_FORMAT_VALUE", "new"); echo json_encode([$r->dumpCached(' . var_export($file, true) . ')]);';
        self::assertSame([false], $this->runPhp($write));
        self::assertSame($before, file_get_contents($this->root . '/' . $file));
    }

    #[DataProvider('artifacts')]
    public function testFutureHeaderCannotBeReadOrOverwritten(string $file): void
    {
        $this->writePayload($file, $this->legacyPayload(), 2);
        $before = file_get_contents($this->root . '/' . $file);
        $code = 'try { SymPress\\Runtime\\Env\\EnvReader::buildFromCacheDump(' . var_export($file, true) . '); } catch (RuntimeException $e) { $r = new SymPress\\Runtime\\Env\\EnvReader(); $r->write("RTV_FORMAT_VALUE", "new"); echo json_encode([$e->getMessage(), $r->dumpCached(' . var_export($file, true) . ')]); }';
        self::assertSame(['Environment cache format is not supported.', false], $this->runPhp($code));
        self::assertSame($before, file_get_contents($this->root . '/' . $file));
    }

    public function testCurrentWritersKeepTheFormatOneContractForCacheAndDump(): void
    {
        $actual = $this->runPhp(<<<'PHP'
$r = new SymPress\Runtime\Env\EnvReader();
$r->write('RTV_FORMAT_VALUE', 'current');
$r->dumpCached('.env.cached.php');
$r->dumpCached('.env.dump.php', immutable: true);
$cache = require '.env.cached.php'; $dump = require '.env.dump.php';
echo json_encode([$cache['format'], $dump['format'], $cache['compatibility'], $dump['sources']]);
PHP);
        self::assertSame([1, 1, true, null], $actual);
    }
}
