<?php

declare(strict_types=1);

namespace SymPress\Runtime\Tests\Integration;

use RuntimeException;
use SymPress\Runtime\Filesystem\Paths;
use SymPress\Runtime\Maintenance\MaintenanceLock;
use SymPress\Runtime\Maintenance\Pruner;
use SymPress\Runtime\Tests\Support\TemporaryProject;

final class PrunerTest extends TemporaryProject
{
    private function payload(string $seed, int $time): string
    {
        $hash = hash('sha256', $seed);
        $path = 'var/runtime/' . $hash;
        $contents = '<?php // @generated by sympress/runtime bootstrap:v1';
        $this->write($path . '/bootstrap.php', $contents);
        $this->write($path . '/manifest.json', json_encode(['format' => 1, 'fingerprint' => $hash, 'files' => ['bootstrap.php' => hash('sha256', $contents)]], JSON_THROW_ON_ERROR));
        touch($this->root . '/' . $path, $time);
        return $this->root . '/' . $path;
    }

    private function config(string $payload, string $file = 'wp-config.php'): void
    {
        $this->write($file, '<?php // @generated by sympress/runtime wp-config:v1' . "\n" . 'require __DIR__ . "/var/runtime/' . basename($payload) . '/bootstrap.php";');
    }

    public function testDryRunAndRetentionPreserveActiveAndNewestInactive(): void
    {
        $active = $this->payload('active', 1);
        $old = $this->payload('old', 2);
        $new = $this->payload('new', 3);
        $this->config($active);
        $paths = new Paths($this->root);
        $plan = (new Pruner())->prune($paths, 1, true);
        self::assertSame([$old], $plan['candidates']);
        self::assertSame([], $plan['removed']);
        self::assertDirectoryExists($old);
        $result = (new Pruner())->prune($paths, 1);
        self::assertSame([$old], $result['removed']);
        self::assertDirectoryExists($active);
        self::assertDirectoryExists($new);
    }

    public function testCustomConfigurationAndUnknownPayloadsArePreserved(): void
    {
        $active = $this->payload('active', 1);
        $custom = $this->payload('custom', 2);
        $unknown = $this->payload('unknown', 3);
        $this->write('var/runtime/' . basename($unknown) . '/user.txt', 'precious');
        $this->config($active);
        $this->config($custom, 'private/config.php');
        self::assertSame([], (new Pruner())->prune(new Paths($this->root), 0, false, 'private/config.php')['removed']);
        self::assertDirectoryExists($custom);
        self::assertDirectoryExists($unknown);
    }

    public function testSymlinkPayloadAndNestedSymlinkArePreserved(): void
    {
        $active = $this->payload('active', 1);
        $other = $this->payload('other', 2);
        $this->config($active);
        symlink($active, $this->root . '/var/runtime/' . hash('sha256', 'link'));
        symlink($active . '/bootstrap.php', $other . '/external.php');
        self::assertSame([], (new Pruner())->prune(new Paths($this->root), 0)['removed']);
        self::assertFileExists($other . '/external.php');
    }

    public function testOnlyOwnedBackupsArePruned(): void
    {
        $active = $this->payload('active', 1);
        $this->config($active);
        $owned = 'var/runtime/package-backups/' . str_repeat('a', 24);
        $unknown = 'var/runtime/package-backups/' . str_repeat('b', 24);
        $this->write($owned . '/user-data', 'old package');
        $this->write($unknown . '/user-data', 'unknown');
        $stat = lstat($this->root . '/' . $owned);
        $this->write($owned . '.json', json_encode(['format' => 1, 'path' => basename($owned), 'dev' => $stat['dev'], 'ino' => $stat['ino']], JSON_THROW_ON_ERROR));
        self::assertSame([$this->root . '/' . $owned], (new Pruner())->prune(new Paths($this->root), 0)['removed']);
        self::assertDirectoryExists($this->root . '/' . $unknown);
    }

    public function testPendingJournalBlocksPrune(): void
    {
        $active = $this->payload('active', 1);
        $this->config($active);
        $this->write('var/runtime/package-layout.pending.json', 'unknown');
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Pending package recovery');
        (new Pruner())->prune(new Paths($this->root), 0);
    }

    public function testGenerationLockBlocksPrune(): void
    {
        $paths = new Paths($this->root);
        $lock = MaintenanceLock::acquire($paths);
        try {
            $this->expectException(RuntimeException::class);
            $this->expectExceptionMessage('maintenance operation');
            (new Pruner())->prune($paths);
        } finally {
            $lock->release();
        }
    }
}
