<?php

declare(strict_types=1);

namespace SymPress\Runtime\Tests\Integration;

use RuntimeException;
use SymPress\Runtime\Application\RunContext;
use SymPress\Runtime\Config\Config;
use SymPress\Runtime\Config\Validator;
use SymPress\Runtime\Console\SetupDrift;
use SymPress\Runtime\Filesystem\Paths;
use SymPress\Runtime\Step\Registry;
use SymPress\Runtime\Tests\Support\TemporaryProject;

final class SetupDriftCoverageTest extends TemporaryProject
{
    /** @param array<string, mixed> $options */
    private function inspector(array $options = []): SetupDrift
    {
        $paths = new Paths($this->root);
        $config = new Config($options, new Validator($paths));
        return new SetupDrift($config, $paths, new RunContext($this->root, $paths->vendor(), $paths->bin()));
    }

    private function fixture(): void
    {
        $this->write('composer.json', '{"name":"fixture/site"}');
        $this->write('vendor/composer/installed.json', '{"packages":[]}');
        $this->write('index.php', '<?php // generated');
    }

    public function testDefaultSelectionIsKnownAndEphemeralCacheDoesNotCauseDrift(): void
    {
        $this->fixture();
        $drift = $this->inspector();
        $drift->record(Registry::DEFAULT_ORDER);
        $this->write('.env.cache.php', '<?php // regenerated by a WordPress request');
        self::assertSame(['changes' => [], 'unknown' => [], 'exit' => 0], $drift->inspect(Registry::DEFAULT_ORDER));
    }

    public function testMetadataOnlyComposerDriftIsReported(): void
    {
        $this->fixture();
        $drift = $this->inspector();
        $drift->record(['index']);
        $this->write('vendor/composer/installed.json', '{"packages":[],"dev":false}');
        self::assertSame([['path' => 'index.php', 'reason' => 'setup-inputs-changed']], $drift->inspect(['index'])['changes']);
    }

    public function testDownloadLockChangeInvalidatesSetupInputs(): void
    {
        $this->fixture();
        $this->write('sympress-runtime.lock', '{"format":1,"downloads":{}}');
        $drift = $this->inspector();
        $drift->record(['index']);
        $this->write('sympress-runtime.lock', '{"format":1,"downloads":{"https://example.test/file":{"sha256":"changed"}}}');
        self::assertSame([['path' => 'index.php', 'reason' => 'setup-inputs-changed']], $drift->inspect(['index'])['changes']);
    }

    public function testNewLocalMuPluginEntryPointInvalidatesLoaderInputs(): void
    {
        $this->fixture();
        $this->write('wp-content/mu-plugins/sympress-runtime-mu-loader.php', '<?php // loader');
        $drift = $this->inspector();
        $drift->record(['muloader']);
        $this->write('wp-content/mu-plugins/local/main.php', '<?php' . "\n" . '/* Plugin Name: Local plugin */');
        self::assertSame([['path' => 'wp-content/mu-plugins/sympress-runtime-mu-loader.php', 'reason' => 'setup-inputs-changed']], $drift->inspect(['muloader'])['changes']);
    }

    public function testMuPluginHeaderAndReadabilityAffectDiscoveryFingerprint(): void
    {
        $this->fixture();
        $plugin = 'wp-content/mu-plugins/local/main.php';
        $this->write($plugin, '<?php' . "\n" . '/* Plugin Name: First name */');
        $this->write('wp-content/mu-plugins/sympress-runtime-mu-loader.php', '<?php // loader');
        $drift = $this->inspector();
        $drift->record(['muloader']);
        $this->write($plugin, '<?php' . "\n" . '/* Plugin Name: Second name */');
        self::assertSame(1, $drift->inspect(['muloader'])['exit']);
        $drift->record(['muloader']);
        $this->write($plugin, '<?php // no plugin header');
        self::assertSame(1, $drift->inspect(['muloader'])['exit']);
        $this->write($plugin, '<?php' . "\n" . '/* Plugin Name: Restored */');
        $drift->record(['muloader']);
        chmod($this->root . '/' . $plugin, 0000);
        clearstatcache(true, $this->root . '/' . $plugin);
        try {
            self::assertFalse(is_readable($this->root . '/' . $plugin), 'The Runtime QA fixture runs as its unprivileged PHP user.');
            self::assertSame(1, $drift->inspect(['muloader'])['exit']);
        } finally {
            chmod($this->root . '/' . $plugin, 0644);
        }
    }

    public function testActiveEnvironmentExistenceIsAnInputWithoutHashingSecretValues(): void
    {
        $this->fixture();
        $this->write('.env.example', 'EXAMPLE=value');
        $drift = $this->inspector(['env-file' => '.custom-env']);
        $drift->record(['envexample']);
        $this->write('.custom-env', 'PRIVATE=first');
        self::assertSame(1, $drift->inspect(['envexample'])['exit']);
        $drift->record(['envexample']);
        $this->write('.custom-env', 'PRIVATE=changed');
        self::assertSame(0, $drift->inspect(['envexample'])['exit']);
        unlink($this->root . '/.custom-env');
        self::assertSame(1, $drift->inspect(['envexample'])['exit']);
    }

    public function testCorrectEnvironmentExampleAndIgnoreTargetsAreCompared(): void
    {
        $this->fixture();
        $this->write('.env.example', 'original');
        $this->write('.gitignore', '/vendor');
        $this->write('.hgignore', 'vendor');
        $drift = $this->inspector(['env-file' => '.custom-env']);
        $drift->record(['envexample', 'vcsignorecheck']);
        $this->write('.env.example', 'changed');
        $this->write('.gitignore', 'changed');
        $this->write('.hgignore', 'changed');
        self::assertSame(['.env.example', '.gitignore', '.hgignore'], array_column($drift->inspect(['envexample', 'vcsignorecheck'])['changes'], 'path'));
    }

    public function testCheckpathsTracksDirectoryExistenceWithoutApplicationFileDrift(): void
    {
        $this->fixture();
        $this->write('wp-content/themes/theme.css', 'original');
        $this->write('wp-content/plugins/plugin.php', 'original');
        $drift = $this->inspector();
        $drift->record(['checkpaths']);
        $this->write('wp-content/plugins/new.php', 'new application file');
        self::assertSame(0, $drift->inspect(['checkpaths'])['exit']);
        chmod($this->root . '/wp-content/themes', 0700);
        clearstatcache();
        self::assertSame(['wp-content/themes'], array_column($drift->inspect(['checkpaths'])['changes'], 'path'));
    }

    public function testMoveContentTracksBothSourceAndDestinationTrees(): void
    {
        $this->fixture();
        $this->write('wp-content/plugin.php', 'original');
        $drift = $this->inspector(['move-content' => true]);
        $drift->record(['movecontent']);
        $this->write('wp-content/plugin.php', 'changed');
        $this->write('wordpress/wp-content/reappeared.php', 'new');
        self::assertSame(['wordpress/wp-content', 'wp-content'], array_column($drift->inspect(['movecontent'])['changes'], 'path'));
    }

    public function testPublishedDevelopmentDropinAndPackageDropinAreTracked(): void
    {
        $this->fixture();
        $this->write('content-dev/object-cache.php', 'source');
        $this->write('vendor/private/dropin/db.php', 'source');
        $this->write('vendor/composer/installed.json', json_encode(['packages' => [['name' => 'private/dropin', 'type' => 'wordpress-dropin', 'version' => '1.0.0', 'install-path' => '../private/dropin']]], JSON_THROW_ON_ERROR));
        $this->write('wp-content/db.php', 'original');
        $this->write('wp-content/object-cache.php', 'original');
        $drift = $this->inspector(['content-dev-dir' => 'content-dev']);
        $drift->record(['dropins', 'publishcontentdev']);
        $this->write('wp-content/db.php', 'changed');
        $this->write('wp-content/object-cache.php', 'changed');
        self::assertSame(['wp-content/db.php', 'wp-content/object-cache.php'], array_column($drift->inspect(['dropins', 'publishcontentdev'])['changes'], 'path'));
    }

    public function testConfiguredLocalDropinSourceContentsAffectInputFingerprint(): void
    {
        $this->fixture();
        $this->write('dropin-source.php', 'original');
        $this->write('wp-content/db.php', 'original');
        $drift = $this->inspector(['dropins' => ['db.php' => 'dropin-source.php']]);
        $drift->record(['dropins']);
        $this->write('dropin-source.php', 'changed');
        self::assertSame([['path' => 'wp-content/db.php', 'reason' => 'setup-inputs-changed']], $drift->inspect(['dropins'])['changes']);
    }

    public function testExistingVersionedPharIsTrackedWithoutRunningIt(): void
    {
        $this->fixture();
        $this->write('wp-cli-2.12.0.phar', '<?php throw new RuntimeException("must not execute");');
        $drift = $this->inspector();
        $drift->record(['wpcli']);
        $this->write('wp-cli-2.12.0.phar', 'changed');
        self::assertSame([['path' => 'wp-cli-2.12.0.phar', 'reason' => 'artifact-changed']], $drift->inspect(['wpcli'])['changes']);
    }

    public function testProvidersExtensionsCommandsAndKernelCacheRemainUnknown(): void
    {
        $this->fixture();
        $this->write('provider.php', '<?php file_put_contents(__DIR__ . "/executed", "bad");');
        $this->write('vendor/composer/installed.json', json_encode(['packages' => [['name' => 'private/extension', 'type' => 'sympress-runtime-extension', 'version' => '1.0.0', 'install-path' => '../private/extension']]], JSON_THROW_ON_ERROR));
        $drift = $this->inspector(['autoload' => 'provider.php', 'wp-cli-commands' => ['wp cache flush']]);
        $drift->record(['index', 'wpcli', 'kernel-cache']);
        $report = $drift->inspect(['index', 'wpcli', 'kernel-cache']);
        self::assertSame(2, $report['exit']);
        self::assertCount(4, $report['unknown']);
        self::assertFileDoesNotExist($this->root . '/executed');
    }

    public function testStateSymlinkAncestorFailsBeforeReadingRecord(): void
    {
        $this->fixture();
        $drift = $this->inspector();
        $drift->record(['index']);
        rename($this->root . '/var', $this->root . '/moved-var');
        symlink('moved-var', $this->root . '/var');
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('symlink ancestor');
        $drift->inspect(['index']);
    }

    public function testConfigurationSymlinkFailsBeforeFollowingPayloadReferences(): void
    {
        $this->fixture();
        $this->write('other-config.php', '<?php // /var/runtime/' . str_repeat('a', 64) . '/bootstrap.php');
        symlink('other-config.php', $this->root . '/wp-config.php');
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('symlink ancestor');
        $this->inspector()->record(['wpconfig']);
    }
}
