<?php

declare(strict_types=1);

namespace SymPress\Runtime\Tests\Integration;

use PHPUnit\Framework\Attributes\Group;
use SymPress\Runtime\Config\Config;
use SymPress\Runtime\Config\Validator;
use SymPress\Runtime\Console\Io;
use SymPress\Runtime\Filesystem\FileContentBuilder;
use SymPress\Runtime\Filesystem\Filesystem;
use SymPress\Runtime\Filesystem\Paths;
use SymPress\Runtime\Filesystem\ProjectBoundary;
use SymPress\Runtime\Process\SystemProcess;
use SymPress\Runtime\Step\Builtin\VcsIgnoreCheckStep;
use SymPress\Runtime\Step\StepInterface;
use SymPress\Runtime\Tests\Support\TemporaryProject;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\BufferedOutput;
use Symfony\Component\Process\ExecutableFinder;
use Symfony\Component\Process\Process;

final class VcsIgnoreStepTest extends TemporaryProject
{
    /** @param list<string> $command */
    private function command(array $command, ?string $root = null): Process
    {
        if ((new ExecutableFinder())->find($command[0]) === null) {
            self::markTestSkipped($command[0] . ' is required for this real VCS integration test.');
        }
        $process = new Process($command, $root ?? $this->root, ['HGRCPATH' => '/dev/null', 'HGPLAIN' => '1', 'GIT_CONFIG_GLOBAL' => '/dev/null', 'GIT_CONFIG_NOSYSTEM' => '1']);
        $process->mustRun();

        return $process;
    }

    /**
     * @param array<string, mixed> $settings
     * @return array{int, string}
     */
    private function check(array $settings = [], ?Paths $paths = null): array
    {
        $paths ??= new Paths($this->root, wp: 'public/wp', content: 'public/content');
        $config = new Config($settings, new Validator($paths));
        $input = new ArrayInput([]);
        $input->setInteractive(false);
        $output = new BufferedOutput();
        $io = new Io($input, $output);
        $step = new VcsIgnoreCheckStep($io, new SystemProcess($paths, $io), new ExecutableFinder(), new FileContentBuilder(), new Filesystem(), new ProjectBoundary($paths));
        $status = $step->allowed($config, $paths) && $step->askConfirm($config, $io) ? $step->run($config, $paths) : StepInterface::NONE;

        return [$status, $output->fetch()];
    }

    #[Group('PAR-STEP-010')]
    #[Group('PAR-OPT-003')]
    #[Group('PAR-VCS-001')]
    public function testGitWithoutCommitsCreatesPreciseRulesAndProtectsCacheDumpAndEnvironmentVariants(): void
    {
        $this->command(['git', 'init', '-q']);
        foreach (['.env', '.env.local', '.env.production', '.env.production.local', '.env.cached.php', '.env.dump.php', 'vendor/package/file', 'public/wp/index.php', 'public/content/plugins/plugin.php', 'public/index.php', 'wp-config.php', 'var/runtime/bundle/bootstrap.php'] as $file) {
            $this->write($file, 'synthetic');
        }
        $this->write('public/assets/site.css', 'owned asset');
        [$status, $output] = $this->check(['check-vcs-ignore' => 'ask', 'create-vcs-ignore-file' => 'ask']);
        self::assertSame(StepInterface::SUCCESS, $status, $output);
        $ignore = file_get_contents($this->root . '/.gitignore');
        self::assertStringContainsString('/.env.dump.php', $ignore);
        self::assertStringContainsString('/wp-cli.yml', $ignore);
        self::assertStringContainsString('/.sympress-runtime.lock.guard', $ignore);
        $this->write('.sympress-runtime.lock.guard', 'created by a subsequent download');
        self::assertSame('', $this->command(['git', 'ls-files', '--others', '--exclude-standard', '--', '.sympress-runtime.lock.guard'])->getOutput());
        $this->write('wp-cli.yml', 'created by the subsequent standard step');
        self::assertStringNotContainsString("\n/public\n", $ignore);
        self::assertStringContainsString('public/assets/site.css', $this->command(['git', 'ls-files', '--others', '--exclude-standard'])->getOutput());
        self::assertSame(StepInterface::SUCCESS, $this->check()[0]);
        self::assertSame($ignore, file_get_contents($this->root . '/.gitignore'));
    }

    #[Group('PAR-VCS-001')]
    public function testGeneratedMarkerIsNotProofAndTrackedSensitiveFilesStillFail(): void
    {
        $this->command(['git', 'init', '-q']);
        $this->write('.env', 'synthetic');
        $this->write('.gitignore', "# @generated by sympress/runtime\n# -~ Generated by WP Starter x~-\n/custom\n");
        $before = file_get_contents($this->root . '/.gitignore');
        [$status, $output] = $this->check();
        self::assertSame(StepInterface::ERROR, $status);
        self::assertStringContainsString('.env', $output);
        self::assertSame($before, file_get_contents($this->root . '/.gitignore'));
        $this->write('.gitignore', "/.env\n/wp-cli.yml\n");
        self::assertSame(StepInterface::SUCCESS, $this->check()[0]);
        $this->command(['git', 'add', '-f', '.env']);
        self::assertSame(StepInterface::ERROR, $this->check()[0]);
    }

    #[Group('PAR-VCS-002')]
    public function testUnknownMetadataAndDisabledCreationNeverClaimVerifiedProtection(): void
    {
        $this->write('.env', 'synthetic');
        [$status, $output] = $this->check();
        self::assertSame(StepInterface::NONE, $status);
        self::assertStringContainsString('unknown', $output);
        self::assertSame(StepInterface::NONE, $this->check(['check-vcs-ignore' => false])[0]);
        $this->command(['git', 'init', '-q']);
        self::assertSame(StepInterface::ERROR, $this->check(['create-vcs-ignore-file' => false])[0]);
        self::assertFileDoesNotExist($this->root . '/.gitignore');
    }

    #[Group('PAR-STEP-010')]
    public function testGitWorktreeMetadataFileIsRecognized(): void
    {
        $this->command(['git', 'init', '-q']);
        $this->command(['git', '-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.test', 'commit', '--allow-empty', '-qm', 'fixture']);
        $worktree = $this->root . '/worktree';
        $this->command(['git', 'worktree', 'add', '-qb', 'fixture-worktree', $worktree]);
        $this->write('worktree/.env', 'synthetic');
        self::assertFileExists($worktree . '/.git');
        self::assertFalse(is_dir($worktree . '/.git'));
        [$status, $output] = $this->check(paths: new Paths($worktree));
        self::assertSame(StepInterface::SUCCESS, $status, $output);
        self::assertFileExists($worktree . '/.gitignore');
    }

    #[Group('PAR-TPL-006')]
    public function testCustomGitTemplateReceivesEscapedPathsAndItsResultIsActuallyChecked(): void
    {
        $this->command(['git', 'init', '-q']);
        $this->write('config [live]/.env', 'synthetic');
        $this->write('custom/.gitignore', "# Custom template\n{{{WPSTARTER_IGNORED_PATHS}}}\n/custom-owned\n");
        $paths = new Paths($this->root);
        $paths->useCustomTemplatesDir($this->root . '/custom');
        [$status, $output] = $this->check(['env-dir' => 'config [live]'], $paths);
        self::assertSame(StepInterface::SUCCESS, $status, $output);
        self::assertStringContainsString('# Custom template', file_get_contents($this->root . '/.gitignore'));
        unlink($this->root . '/.gitignore');
        $this->write('custom/.gitignore', "# No actual rules\n");
        self::assertSame(StepInterface::ERROR, $this->check(['env-dir' => 'config [live]'], $paths)[0]);
    }

    #[Group('PAR-STEP-010')]
    #[Group('PAR-TPL-006')]
    public function testMercurialCreatesWorkingRulesAndFindsUnprotectedAndTrackedFiles(): void
    {
        $this->command(['hg', 'init']);
        $this->write('.env', 'synthetic');
        $this->write('public/wp/index.php', 'core');
        [$status, $output] = $this->check();
        self::assertSame(StepInterface::SUCCESS, $status, $output);
        $this->write('.hgignore', "# @generated by sympress/runtime\n");
        self::assertSame(StepInterface::ERROR, $this->check()[0]);
        $this->command(['hg', 'add', '.env']);
        $this->write('.hgignore', "syntax: regexp\n^\\.env$\n^public/wp(?:/|$)\n");
        self::assertSame(StepInterface::ERROR, $this->check()[0]);
    }

    #[Group('PAR-STEP-010')]
    public function testSubversionInspectsIgnorePropertiesWithoutCreatingAnIgnoreFile(): void
    {
        $this->command(['svnadmin', 'create', $this->root . '/repository']);
        $worktree = $this->root . '/working-copy';
        $this->command(['svn', 'checkout', '-q', 'file://' . $this->root . '/repository', $worktree]);
        $this->write('working-copy/.env', 'synthetic');
        $paths = new Paths($worktree);
        self::assertSame(StepInterface::ERROR, $this->check(paths: $paths)[0]);
        $this->command(['svn', 'propset', 'svn:ignore', '.env', '.'], $worktree);
        [$status, $output] = $this->check(paths: $paths);
        self::assertSame(StepInterface::SUCCESS, $status, $output);
        self::assertFileDoesNotExist($worktree . '/.svnignore');
    }
}
