<?php

declare(strict_types=1);

namespace SymPress\Runtime\Env;

use RuntimeException;
use Throwable;

/** @internal */
final class EnvCacheFormat
{
    private const string HEADER = "<?php\n// @generated by sympress/runtime env-cache:v1\n";

    /** @return array<array-key, mixed> */
    public static function read(string $file, bool $dataOnly = false): array
    {
        $header = file_get_contents($file, false, null, 0, strlen(self::HEADER));
        if ($header !== self::HEADER) {
            throw new RuntimeException('Environment cache format is not supported.');
        }
        try {
            if ($dataOnly) {
                $source = file_get_contents($file);
                if (!is_string($source)) {
                    throw new RuntimeException('Cannot read environment cache.');
                }
                $data = (new EnvCacheLiteral())->decode($source);
            }
            $data = $dataOnly ? $data : (static fn (string $path): mixed => require $path)($file);
        } catch (Throwable) {
            throw new RuntimeException('Cannot read environment cache.');
        }
        // Validate before stale sources can turn a future format into a cache miss.
        if (!is_array($data) || ($data['format'] ?? null) !== 1) {
            throw new RuntimeException('Environment cache format is not supported.');
        }
        return $data;
    }

    /** @param array<string, mixed> $payload */
    public static function encode(array $payload): string
    {
        return self::HEADER . 'return ' . var_export($payload, true) . ";\n";
    }

    public static function canReplace(string $file): bool
    {
        if (!is_file($file)) {
            return true;
        }
        // Only replace canonical generated version-1 data. Inspect bytes without
        // executing existing PHP merely to decide whether it may be overwritten.
        $prefix = self::HEADER . "return array (\n  'format' => 1,\n";
        return file_get_contents($file, false, null, 0, strlen($prefix)) === $prefix;
    }
}
