<?php
// @generated by sympress/runtime mu-loader:v1
/**
 * Plugin Name: SymPress Runtime MU loader
 * Version: {{{RUNTIME_VERSION}}}
 * Description: Loads the discovered Composer and local MU plugin entry points.
 */

if ({{{MU_NATIVE}}}) {
    $runtimeMuPlugins = (static function (array $entries): array {
        $directory = defined('WPMU_PLUGIN_DIR') ? WPMU_PLUGIN_DIR : __DIR__;
        $plugins = [];
        foreach ($entries as $entry) {
            $file = wp_normalize_path($directory . '/' . $entry);
            if (is_file($file)) {
                $plugins[$entry] = $file;
            }
        }
        add_filter('plugins_list', static function (array $groups) use ($plugins): array {
            if (empty($groups['mustuse']) || !is_array($groups['mustuse'])) {
                return $groups;
            }
            foreach ($plugins as $entry => $file) {
                $metadata = get_plugin_data($file, false, false);
                if (empty($metadata['Name'])) {
                    $metadata['Name'] = basename(dirname($file));
                }
                $groups['mustuse'][$entry] = $metadata;
            }
            uasort($groups['mustuse'], '_sort_uname_callback');

            return $groups;
        });

        return $plugins;
    })({{{MU_PLUGINS_ARRAY}}});

    foreach ($runtimeMuPlugins as $runtimeMuPath) {
        // Like WordPress itself, include plugins in the caller's global scope.
        require_once $runtimeMuPath;
        do_action('mu_plugin_loaded', $runtimeMuPath);
    }
    unset($runtimeMuPlugins, $runtimeMuPath);
} else {
    foreach ({{{MU_PLUGINS_ARRAY}}} as $runtimeMuPlugin) {
        $runtimeMuPath = wp_normalize_path(__DIR__ . '/' . $runtimeMuPlugin);
        if (is_file($runtimeMuPath)) {
            require_once $runtimeMuPath;
        }
    }
    unset($runtimeMuPlugin, $runtimeMuPath);
}
