<?php
// @generated by sympress/runtime mu-loader:v1
/**
 * Plugin Name: SymPress Runtime MU loader
 * Description: Loads the discovered Composer and local MU plugin entry points.
 */

foreach ({{{MU_PLUGINS_ARRAY}}} as $runtimeMuPlugin) {
    $runtimeMuPath = wp_normalize_path(__DIR__ . '/' . $runtimeMuPlugin);
    if (is_file($runtimeMuPath)) {
        require_once $runtimeMuPath;
    }
}
unset($runtimeMuPlugin, $runtimeMuPath);
