<?php
// @generated by sympress/runtime wp-config-proxy:v1
defined('SYMPRESS_RUNTIME_WP_CONFIG_PATH') || define('SYMPRESS_RUNTIME_WP_CONFIG_PATH', {{{CONFIG_PATH}}});
if ({{{COMPATIBILITY}}}) {
    defined('WP_STARTER_WP_CONFIG_PATH') || define('WP_STARTER_WP_CONFIG_PATH', SYMPRESS_RUNTIME_WP_CONFIG_PATH);
}
require_once SYMPRESS_RUNTIME_WP_CONFIG_PATH;
