<?php
// @generated by sympress/runtime wp-config:v1

DEBUG_INFO_INIT : {
    $debugInfo = [];
} #@@/DEBUG_INFO_INIT

ABSPATH : {
    defined('ABSPATH') || define('ABSPATH', rtrim({{{CORE_PATH}}}, '/\\') . '/');
    require_once ABSPATH . 'wp-includes/plugin.php';
} #@@/ABSPATH

AUTOLOAD : {
    if ({{{PROJECT_AUTOLOAD_ENABLED}}}) {
        require_once {{{PROJECT_AUTOLOAD_PATH}}};
    }
    $runtimeReaderClass = require {{{PAYLOAD_PATH}}};
    defined('SYMPRESS_RUNTIME_PATH') || define('SYMPRESS_RUNTIME_PATH', {{{ROOT_PATH}}});
    defined('SYMPRESS_RUNTIME_ENV_PATH') || define('SYMPRESS_RUNTIME_ENV_PATH', {{{ENV_PATH}}});
    if ({{{COMPATIBILITY}}}) {
        defined('WPSTARTER_PATH') || define('WPSTARTER_PATH', {{{LEGACY_PROJECT_PATH}}});
        defined('WPSTARTER_ENV_PATH') || define('WPSTARTER_ENV_PATH', SYMPRESS_RUNTIME_ENV_PATH);
    }
    $debugInfo['base-path'] = ['label' => 'Project root path', 'value' => SYMPRESS_RUNTIME_PATH, 'debug' => SYMPRESS_RUNTIME_PATH];
    $debugInfo['env-path'] = ['label' => 'Environment path', 'value' => SYMPRESS_RUNTIME_ENV_PATH, 'debug' => SYMPRESS_RUNTIME_ENV_PATH];
    $debugInfo['runtime-payload'] = ['label' => 'Runtime payload', 'value' => {{{PAYLOAD_ID}}}, 'debug' => {{{PAYLOAD_ID}}}];
} #@@/AUTOLOAD

WPS_GETENV_FUNCTION : {
    $envCacheFile = SYMPRESS_RUNTIME_ENV_PATH . '/.env.cached.php';
    $envDumpFile = SYMPRESS_RUNTIME_ENV_PATH . '/.env.dump.php';
    $usingEnvDump = is_file($envDumpFile);
    global $sympressRuntimeEnvironment;
    $sympressRuntimeEnvironment = $usingEnvDump || {{{CACHE_ENABLED}}}
        ? $runtimeReaderClass::buildFromCacheDump($usingEnvDump ? $envDumpFile : $envCacheFile, {{{PROFILE}}}, compatibility: {{{COMPATIBILITY}}})
        : new $runtimeReaderClass(profile: {{{PROFILE}}}, compatibility: {{{COMPATIBILITY}}});
    if (!function_exists('sympress_runtime_getenv')) {
        function sympress_runtime_getenv(?string $name): bool|int|float|string|object|null
        {
            static $reader;
            if ($name === '') {
                throw new InvalidArgumentException('Environment variable name must not be empty.');
            }
            if ($reader !== null && $name === null) {
                throw new TypeError('Environment reader is already initialized; provide a variable name.');
            }
            $reader ??= $GLOBALS['sympressRuntimeEnvironment'];
            return $name === null ? $reader : $reader->read($name);
        }
    }
    if (!function_exists('sympress_runtime_deprecated')) {
        function sympress_runtime_deprecated(string $name, string $replacement): void
        {
            static $reported = [];
            if (isset($reported[$name])) { return; }
            $reported[$name] = true;
            if (PHP_SAPI !== 'cli') {
                if (function_exists('do_action')) { do_action('deprecated_function_run', $name, $replacement, '0.1.0'); }
                error_log($name . ' is deprecated; use ' . $replacement . '.');
                return;
            }
            if (function_exists('_deprecated_function')) {
                _deprecated_function($name, '0.1.0', $replacement);
            } else {
                trigger_error($name . ' is deprecated; use ' . $replacement . '.', E_USER_DEPRECATED);
            }
        }
    }
    $envLoader = sympress_runtime_getenv(null);
    if ({{{COMPATIBILITY}}} && !function_exists('wpstarter_getenv')) {
        function wpstarter_getenv(?string $name): bool|int|float|string|object|null
        {
            sympress_runtime_deprecated('wpstarter_getenv', 'sympress_runtime_getenv');
            return sympress_runtime_getenv($name);
        }
    }
} #@@/WPS_GETENV_FUNCTION

ENV_VARIABLES : {
    $envIsCached = $envLoader->hasCachedValues();
    $envLoader->loadChain({{{ENV_FILENAME}}}, SYMPRESS_RUNTIME_ENV_PATH, {{{LOCAL_OVERRIDES}}});
    $envLoader->setupConstants();
    $envLoader->setupKernelBuildId(SYMPRESS_RUNTIME_PATH . '/var/runtime', {{{KERNEL_BUILD_ID}}});
    $envType = $envLoader->determineEnvType();
    if (str_contains($envType, '/') || str_contains($envType, '\\') || str_contains($envType, "\0")) {
        throw new RuntimeException('Invalid environment bootstrap name.');
    }
    $phpEnvFile = {{{ENV_BOOTSTRAP_PATH}}} . '/' . $envType . '.php';
    $hasPhpEnvFile = is_file($phpEnvFile) && is_readable($phpEnvFile);
    if ($hasPhpEnvFile) { require_once $phpEnvFile; }
    $debugInfo['env-type'] = ['label' => 'Raw environment', 'value' => $envType, 'debug' => $envType];
    $debugInfo['wp-env-type'] = ['label' => 'WordPress environment', 'value' => WP_ENVIRONMENT_TYPE, 'debug' => WP_ENVIRONMENT_TYPE];
    $debugInfo['env-cache-file'] = ['label' => 'Environment cache', 'value' => is_file($envCacheFile) ? $envCacheFile : 'None', 'debug' => is_file($envCacheFile) ? $envCacheFile : false];
    $debugInfo['env-cache-enabled'] = ['label' => 'Cache enabled', 'value' => {{{CACHE_ENABLED}}} ? 'Yes' : 'No', 'debug' => {{{CACHE_ENABLED}}}];
    $debugInfo['cached-env'] = ['label' => 'Environment from cache', 'value' => $envIsCached ? 'Yes' : 'No', 'debug' => $envIsCached];
    $debugInfo['env-dump-file'] = ['label' => 'Environment dump', 'value' => $usingEnvDump ? $envDumpFile : 'None', 'debug' => $usingEnvDump ? $envDumpFile : false];
    $debugInfo['env-php-file'] = ['label' => 'Environment PHP file', 'value' => $hasPhpEnvFile ? $phpEnvFile : 'None', 'debug' => $hasPhpEnvFile ? $phpEnvFile : ''];
} #@@/ENV_VARIABLES

KEYS : {
{{{SALT_DEFINITIONS}}}
} #@@/KEYS

DB_SETUP : {
    defined('DB_HOST') || define('DB_HOST', 'localhost');
    defined('DB_CHARSET') || define('DB_CHARSET', 'utf8');
    defined('DB_COLLATE') || define('DB_COLLATE', '');
    global $table_prefix;
    $table_prefix = $envLoader->read('DB_TABLE_PREFIX') ?: 'wp_';
} #@@/DB_SETUP

EARLY_HOOKS : {
    $earlyHookFile = {{{EARLY_HOOK_PATH}}};
    $hasEarlyHook = $earlyHookFile !== '' && is_file($earlyHookFile) && is_readable($earlyHookFile);
    if ($hasEarlyHook) { require_once $earlyHookFile; }
    $debugInfo['early-hooks-file'] = ['label' => 'Early hooks file', 'value' => $hasEarlyHook ? $earlyHookFile : 'None', 'debug' => $hasEarlyHook ? $earlyHookFile : ''];
} #@@/EARLY_HOOKS

DEFAULT_ENV : {
    $runtimeDefaults = match (WP_ENVIRONMENT_TYPE) {
        'local' => ['WP_LOCAL_DEV' => true, 'WP_DEVELOPMENT_MODE' => 'all', 'WP_DEBUG' => true, 'WP_DEBUG_DISPLAY' => true, 'WP_DEBUG_LOG' => false, 'SAVEQUERIES' => true, 'SCRIPT_DEBUG' => true, 'WP_DISABLE_FATAL_ERROR_HANDLER' => true],
        'development' => ['WP_DEBUG' => true, 'WP_DEBUG_DISPLAY' => true, 'WP_DEBUG_LOG' => false, 'SAVEQUERIES' => true, 'SCRIPT_DEBUG' => true, 'WP_DISABLE_FATAL_ERROR_HANDLER' => true],
        'staging' => ['WP_DEBUG' => true, 'WP_DEBUG_DISPLAY' => false, 'WP_DEBUG_LOG' => true, 'SAVEQUERIES' => false, 'SCRIPT_DEBUG' => true],
        default => ['WP_DEBUG' => false, 'WP_DEBUG_DISPLAY' => false, 'WP_DEBUG_LOG' => false, 'SAVEQUERIES' => false, 'SCRIPT_DEBUG' => false],
    };
    foreach ($runtimeDefaults as $runtimeName => $runtimeValue) {
        defined($runtimeName) || define($runtimeName, $runtimeValue);
    }
} #@@/DEFAULT_ENV

SSL_FIX : {
    $runtimeSslFix = $envLoader->read('WP_FORCE_SSL_FORWARDED_PROTO')
        && is_string($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? null)
        && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https';
    if ($runtimeSslFix) { $_SERVER['HTTPS'] = 'on'; }
    $debugInfo['ssl-fix'] = ['label' => 'Forwarded SSL', 'value' => $runtimeSslFix ? 'Yes' : 'No', 'debug' => $runtimeSslFix];
} #@@/SSL_FIX

URL_CONSTANTS : {
    if (!defined('WP_HOME')) {
        $runtimePort = is_numeric($_SERVER['SERVER_PORT'] ?? '') ? (int) $_SERVER['SERVER_PORT'] : 0;
        $runtimeScheme = isset($_SERVER['HTTPS']) ? (filter_var($_SERVER['HTTPS'], FILTER_VALIDATE_BOOLEAN) ? 'https' : 'http') : ($runtimePort === 443 ? 'https' : 'http');
        $runtimeHost = is_string($_SERVER['SERVER_NAME'] ?? null) ? $_SERVER['SERVER_NAME'] : 'localhost';
        $runtimeHome = $runtimeScheme . '://' . $runtimeHost;
        if ($runtimePort > 0 && $runtimePort !== ($runtimeScheme === 'https' ? 443 : 80)) { $runtimeHome .= ':' . $runtimePort; }
        define('WP_HOME', $runtimeHome);
    }
    defined('WP_SITEURL') || define('WP_SITEURL', rtrim(WP_HOME, '/') . '/' . {{{CORE_URL_PATH}}});
    defined('WP_CONTENT_DIR') || define('WP_CONTENT_DIR', {{{CONTENT_PATH}}});
    defined('WP_CONTENT_URL') || define('WP_CONTENT_URL', rtrim(WP_HOME, '/') . '/' . {{{CONTENT_URL_PATH}}});
} #@@/URL_CONSTANTS

THEMES_REGISTER : {
    if ({{{REGISTER_THEMES}}}) {
        add_action('plugins_loaded', static function (): void { register_theme_directory(ABSPATH . 'wp-content/themes'); });
    }
    $debugInfo['register-core-themes'] = ['label' => 'Register core themes', 'value' => {{{REGISTER_THEMES}}} ? 'Yes' : 'No', 'debug' => {{{REGISTER_THEMES}}}];
} #@@/THEMES_REGISTER

ADMIN_COLOR : {
    add_filter('get_user_option_admin_color', static function ($color) use ($envLoader) { return $envLoader->read('WP_ADMIN_COLOR') ?: $color; }, 999);
} #@@/ADMIN_COLOR

ENV_CACHE : {
    if ({{{CACHE_ENABLED}}} && !$usingEnvDump && $envLoader->isWpSetup()) {
        register_shutdown_function(static function () use ($envLoader, $envType, $envCacheFile): void {
            $skip = $envType === 'local' || (defined('WP_DEVELOPMENT_MODE') && WP_DEVELOPMENT_MODE);
            if ({{{COMPATIBILITY}}} && has_filter('wpstarter.skip-cache-env')) {
                sympress_runtime_deprecated('wpstarter.skip-cache-env', 'sympress.runtime.skip-cache-env');
                $skip = apply_filters('wpstarter.skip-cache-env', $skip, $envType);
            }
            if (!apply_filters('sympress.runtime.skip-cache-env', $skip, $envType)) { $envLoader->dumpCached($envCacheFile); }
        });
    }
} #@@/ENV_CACHE

DEBUG_INFO : {
    add_filter('debug_information', static function ($info) use ($debugInfo): array {
        $info = is_array($info) ? $info : [];
        $info['sympress-runtime'] = ['label' => 'SymPress Runtime', 'fields' => $debugInfo];
        return $info;
    }, 30);
} #@@/DEBUG_INFO

GETENV_FILTER : {
    // Current kernel discovery accepts library packages and this public bundle filter.
    add_filter('symfony_register_bundles', static function ($bundles) {
        if (is_array($bundles) && class_exists(\SymPress\Kernel\Bundle\AbstractBundle::class) && class_exists(\SymPress\Runtime\Bridge\Kernel\RuntimeBundle::class)) {
            $bundles[\SymPress\Runtime\Bridge\Kernel\RuntimeBundle::class] = ['all' => true];
        }
        return $bundles;
    });
    if ({{{COMPATIBILITY}}}) {
        add_filter('getenv', static function ($name) use ($envLoader) {
            sympress_runtime_deprecated('getenv filter', 'sympress_runtime_getenv');
            return is_string($name) && $name !== '' ? $envLoader->read($name) : null;
        }, PHP_INT_MAX);
    }
} #@@/GETENV_FILTER

BEFORE_BOOTSTRAP : {
} #@@/BEFORE_BOOTSTRAP

CLEAN_UP : {
    unset($debugInfo, $envType, $envLoader, $sympressRuntimeEnvironment, $envCacheFile, $envDumpFile, $usingEnvDump, $envIsCached, $runtimeReaderClass, $phpEnvFile, $hasPhpEnvFile, $earlyHookFile, $hasEarlyHook, $runtimeDefaults, $runtimeName, $runtimeValue, $runtimeSslFix, $runtimePort, $runtimeScheme, $runtimeHost, $runtimeHome);
} #@@/CLEAN_UP

WP_CLI_HACK : {
    if (defined('WP_CLI') && WP_CLI && (defined('SYMPRESS_RUNTIME_WP_CONFIG_PATH') || defined('WP_STARTER_WP_CONFIG_PATH'))) { return; }
} #@@/WP_CLI_HACK

require_once ABSPATH . 'wp-settings.php';
