<?php

declare(strict_types=1);

namespace SymPress\Runtime\Maintenance;

use RuntimeException;
use SymPress\Runtime\Filesystem\Paths;
use SymPress\Runtime\Filesystem\ProjectBoundary;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Path;

/**
 * Explicit retention of verified Runtime artifacts; unknown trees are preserved.
 *
 * @internal
 */
final class Pruner
{
    /** @return array{candidates: list<string>, removed: list<string>, retained: list<string>} */
    public function prune(Paths $paths, int $keep = 2, bool $dryRun = false, ?string $configFile = null): array
    {
        if ($keep < 0) {
            throw new RuntimeException('Retention count must be zero or greater.');
        }
        $maintenance = MaintenanceLock::acquire($paths);
        $layout = null;
        try {
            $lockFile = $paths->vendor('composer/.sympress-layout.lock');
            (new ProjectBoundary($paths))->assertWritablePath($lockFile);
            if (is_link($lockFile)) {
                throw new RuntimeException('Package lock must not be a symlink.');
            }
            if (is_dir(dirname($lockFile))) {
                $layout = fopen($lockFile, 'c');
                if ($layout === false || !flock($layout, LOCK_EX | LOCK_NB)) {
                    throw new RuntimeException('Package recovery is running.');
                }
            }
            return $this->pruneLocked($paths, $keep, $dryRun, $configFile);
        } finally {
            if (is_resource($layout)) {
                flock($layout, LOCK_UN);
                fclose($layout);
            }
            $maintenance->release();
        }
    }

    /** @return array{candidates: list<string>, removed: list<string>, retained: list<string>} */
    private function pruneLocked(Paths $paths, int $keep, bool $dryRun, ?string $configFile): array
    {
        $directory = $paths->root('var/runtime');
        $this->noLinks($directory, $paths->root());
        $result = ['candidates' => [], 'removed' => [], 'retained' => []];
        // An interrupted transaction may reference any of the old/new artifacts.
        if (file_exists($directory . '/package-layout.pending.json') || is_link($directory . '/package-layout.pending.json')) {
            throw new RuntimeException('Pending package recovery must complete before pruning.');
        }
        $active = [];
        $configs = array_unique([$paths->root('wp-config.php'), $paths->wpParent('wp-config.php'), ...($configFile === null ? [] : [Path::makeAbsolute($configFile, $paths->root())])]);
        foreach ($configs as $file) {
            if (!file_exists($file) && !is_link($file)) {
                continue;
            }
            $this->noLinks($file, $paths->root());
            $contents = file_get_contents($file);
            if ($contents === false || !str_contains($contents, '@generated by sympress/runtime wp-config')) {
                throw new RuntimeException('Cannot establish active payload references from configuration.');
            }
            preg_match_all('~var/runtime/([a-f0-9]{64})/bootstrap\.php~', $contents, $matches);
            if ($matches[1] === [] && !str_contains($contents, 'wp-config-proxy:v1')) {
                throw new RuntimeException('Configuration payload reference is not recognized.');
            }
            foreach ($matches[1] as $fingerprint) {
                $active[$directory . '/' . $fingerprint] = true;
            }
        }
        if ($active === []) {
            throw new RuntimeException('No active generated configuration found; pruning stopped.');
        }
        $groups = [[], []];
        foreach (glob($directory . '/*') ?: [] as $path) {
            if (preg_match('/^[a-f0-9]{64}$/D', basename($path)) !== 1) {
                continue;
            }
            if (isset($active[$path]) || !$this->payload($path)) {
                $result['retained'][] = $path;
                continue;
            }
            $groups[0][] = $path;
        }
        $backups = $directory . '/package-backups';
        if (is_dir($backups) && !is_link($backups)) {
            foreach (glob($backups . '/*') ?: [] as $path) {
                if (preg_match('/^[a-f0-9]{24}$/D', basename($path)) !== 1) {
                    continue;
                }
                if (!$this->backup($path)) {
                    $result['retained'][] = $path;
                    continue;
                }
                $groups[1][] = $path;
            }
        }
        foreach ($groups as $kind => $group) {
            usort($group, static fn (string $left, string $right): int => (filemtime($right . ($kind === 1 ? '.json' : '')) <=> filemtime($left . ($kind === 1 ? '.json' : ''))) ?: strcmp($left, $right));
            array_push($result['retained'], ...array_slice($group, 0, $keep));
            array_push($result['candidates'], ...array_slice($group, $keep));
        }
        if (!$dryRun) {
            foreach ($result['candidates'] as $path) {
                (new Filesystem())->remove($path);
                if (dirname($path) === $backups) {
                    (new Filesystem())->remove($path . '.json');
                }
                $result['removed'][] = $path;
            }
        }

        return $result;
    }

    private function noLinks(string $path, string $root): void
    {
        if (!Path::isBasePath($root, $path)) {
            throw new RuntimeException('Prune paths must remain inside the project.');
        }
        for ($part = $path; $part !== $root; $part = dirname($part)) {
            if (is_link($part)) {
                throw new RuntimeException('Prune paths must not traverse symlinks.');
            }
        }
    }

    private function payload(string $path): bool
    {
        if (!is_dir($path) || is_link($path) || is_link($path . '/manifest.json') || !is_file($path . '/manifest.json')) {
            return false;
        }
        $manifest = json_decode((string) file_get_contents($path . '/manifest.json'), true);
        if (!is_array($manifest) || ($manifest['format'] ?? null) !== 1 || ($manifest['fingerprint'] ?? null) !== basename($path) || !is_array($manifest['files'] ?? null) || !isset($manifest['files']['bootstrap.php'])) {
            return false;
        }
        $actual = $this->files($path);
        if ($actual === null) {
            return false;
        }
        $expected = array_keys($manifest['files']);
        $expected[] = 'manifest.json';
        sort($expected);
        sort($actual);
        if ($actual !== $expected) {
            return false;
        }
        foreach ($manifest['files'] as $file => $hash) {
            if (!is_string($file) || !is_string($hash) || !hash_equals($hash, (string) hash_file('sha256', $path . '/' . $file))) {
                return false;
            }
        }
        return str_contains((string) file_get_contents($path . '/bootstrap.php'), '@generated by sympress/runtime bootstrap:v1');
    }

    private function backup(string $path): bool
    {
        if (!is_dir($path) || is_link($path) || !is_file($path . '.json') || is_link($path . '.json') || $this->files($path) === null) {
            return false;
        }
        $receipt = json_decode((string) file_get_contents($path . '.json'), true);
        $stat = lstat($path);
        return is_array($receipt) && $stat !== false && ($receipt['format'] ?? null) === 1 && ($receipt['path'] ?? null) === basename($path) && ($receipt['dev'] ?? null) === $stat['dev'] && ($receipt['ino'] ?? null) === $stat['ino'];
    }

    /** @return list<string>|null */
    private function files(string $root, string $relative = ''): ?array
    {
        $files = [];
        foreach (scandir($root . ($relative === '' ? '' : '/' . $relative)) ?: [] as $name) {
            if ($name === '.' || $name === '..') {
                continue;
            }
            $entry = $relative === '' ? $name : $relative . '/' . $name;
            $path = $root . '/' . $entry;
            if (is_link($path)) {
                return null;
            }
            if (is_dir($path)) {
                $nested = $this->files($root, $entry);
                if ($nested === null) {
                    return null;
                }
                array_push($files, ...$nested);
                continue;
            }
            if (!is_file($path)) {
                return null;
            }
            $files[] = $entry;
        }
        return $files;
    }
}
