<?php

declare(strict_types=1);

namespace SymPress\Runtime\Step\Builtin;

use RuntimeException;
use SymPress\Runtime\Config\Config;
use SymPress\Runtime\Console\Io;
use SymPress\Runtime\Download\UrlDownloader;
use SymPress\Runtime\Filesystem\Filesystem;
use SymPress\Runtime\Filesystem\Paths;
use SymPress\Runtime\Step\ConditionalStepInterface;
use SymPress\Runtime\Step\FileCreationStepInterface;
use SymPress\Runtime\Step\OptionalStepInterface;
use Symfony\Component\Filesystem\Path;

/** @internal */
final class EnvExampleStep implements FileCreationStepInterface, OptionalStepInterface, ConditionalStepInterface
{
    private string $failure = 'Cannot save the environment example.';

    public function __construct(private readonly Config $config, private readonly Filesystem $files, private readonly UrlDownloader $downloader)
    {
    }

    public function name(): string
    {
        return 'envexample';
    }

    private function directory(Paths $paths): string
    {
        $directory = $this->config['compatibility-profile']->is('release-3.0.1') ? $paths->root() : $this->config['env-dir']->unwrapOrFallback($paths->root());
        if (!is_string($directory)) {
            throw new RuntimeException('Invalid environment example directory.');
        }

        return $directory;
    }

    public function allowed(Config $config, Paths $paths): bool
    {
        $file = $config['env-file']->unwrapOrFallback('.env');

        return is_string($file) && $config['env-example']->not(false) && !is_file($this->directory($paths) . '/' . $file);
    }

    public function targetPath(Paths $paths): string
    {
        return rtrim($this->directory($paths), '/\\') . '/.env.example';
    }

    public function askConfirm(Config $config, Io $io): bool
    {
        return $config['env-example']->not(self::ASK) || $io->askConfirm('Save an environment example?', true);
    }

    public function run(Config $config, Paths $paths): int
    {
        $source = $config['env-example']->unwrapOrFallback(false);
        if ($source === false || $source === '') {
            return self::NONE;
        }
        $isUrl = is_string($source) && filter_var($source, FILTER_VALIDATE_URL);
        $content = false;
        if ($isUrl) {
            $temporary = tempnam(sys_get_temp_dir(), 'sympress-example-');
            if ($temporary === false) {
                return self::ERROR;
            }
            try {
                if (!$this->downloader->save($source, $temporary)) {
                    $this->failure = $this->downloader->error();

                    return self::ERROR;
                }
                $content = file_get_contents($temporary);
                if ($content === false) {
                    return self::ERROR;
                }
            } finally {
                unlink($temporary);
            }
        }
        if (!$isUrl) {
            $file = is_string($source) && $source !== self::ASK ? Path::makeAbsolute($source, $paths->root()) : $paths->template('.env.example');
            $content = is_file($file) && is_readable($file) ? file_get_contents($file) : false;
            if ($content === false) {
                return self::ERROR;
            }
        }
        if ($config['compatibility-profile']->is('native') && !str_contains($content, '@generated by sympress/runtime')) {
            $content = "# @generated by sympress/runtime env-example:v1\n" . $content;
        }

        return $this->files->save($content, $this->targetPath($paths)) ? self::SUCCESS : self::ERROR;
    }

    public function success(): string
    {
        return 'Environment example saved.';
    }

    public function error(): string
    {
        return $this->failure;
    }

    public function conditionsNotMet(): string
    {
        return 'Environment example is disabled or the configured environment file exists.';
    }

    public function skipped(): string
    {
        return 'Environment example creation declined.';
    }
}
